// <auto-generated />
using System;
using LowYurt3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LowYurt3.Migrations
{
    [DbContext(typeof(LowYurtContext))]
    partial class LowYurtContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LowYurt3.Models.Admin", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Admin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<byte[]>("ContraseñaAdmin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("Contraseña_admin");

                    b.Property<string>("CorreoAdmin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Correo_Admin");

                    b.Property<string>("NombreAdmin")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Nombre_Admin");

                    b.HasKey("IdAdmin")
                        .HasName("PK__Admin__3F48CD797C849503");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("LowYurt3.Models.Categorium", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("NombreCategoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre_Categoria");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__CB9033498D28ED89");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("LowYurt3.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("Contraseña")
                        .HasMaxLength(45)
                        .HasColumnType("varbinary(45)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Segundo_Apellido");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Segundo_Nombre");

                    b.Property<long>("Telefono")
                        .HasColumnType("bigint");

                    b.HasKey("IdCliente")
                        .HasName("PK__Cliente__3DD0A8CB3BDD35E1");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("LowYurt3.Models.EnvioPedido", b =>
                {
                    b.Property<int>("IdEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Envio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnvio"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("Id_Cliente");

                    b.Property<int>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("Id_Pago");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("Id_Pedido");

                    b.Property<int>("IdPedidoNavigationIdPedido")
                        .HasColumnType("int");

                    b.HasKey("IdEnvio")
                        .HasName("PK__Envio_Pe__3A8388337EACD537");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdPago");

                    b.HasIndex("IdPedidoNavigationIdPedido");

                    b.ToTable("Envio_Pedido", (string)null);
                });

            modelBuilder.Entity("LowYurt3.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int>("IdClienteNavigationIdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("Id_Pedido");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Metodo_Pago");

                    b.Property<int>("PagoTotal")
                        .HasColumnType("int")
                        .HasColumnName("Pago_Total");

                    b.Property<int>("PedidoIdPedido")
                        .HasColumnType("int");

                    b.Property<int?>("ValorEnvio")
                        .HasColumnType("int")
                        .HasColumnName("Valor_Envio");

                    b.HasKey("IdPago")
                        .HasName("PK__Pago__3E79AD9A1F589008");

                    b.HasIndex("IdClienteNavigationIdCliente");

                    b.HasIndex("IdPedido");

                    b.HasIndex("PedidoIdPedido");

                    b.ToTable("Pago", (string)null);
                });

            modelBuilder.Entity("LowYurt3.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<int>("CantidadProductos")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad_Productos");

                    b.Property<DateTime?>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha_Compra")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("Id_Cliente");

                    b.Property<int>("ValorTotal")
                        .HasColumnType("int")
                        .HasColumnName("Valor_Total");

                    b.HasKey("IdPedido")
                        .HasName("PK__Pedido__A5D00139DB9C6294");

                    b.HasIndex("IdCliente");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("LowYurt3.Models.PedidoDetalle", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("Id_Pedido");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("Id_Producto");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("PedidoIdPedido")
                        .HasColumnType("int");

                    b.HasKey("IdPedido", "IdProducto")
                        .HasName("PK__Pedido_D__47D85BA59CF9F2AC");

                    b.HasIndex("IdProducto");

                    b.HasIndex("PedidoIdPedido");

                    b.ToTable("Pedido_Detalle", (string)null);
                });

            modelBuilder.Entity("LowYurt3.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("Id_Categoria");

                    b.Property<string>("ImagenProducto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Imagen_Producto");

                    b.Property<string>("NombreProducto")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre_Producto");

                    b.Property<int>("ValorUnitario")
                        .HasColumnType("int")
                        .HasColumnName("Valor_Unitario");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__2085A9CF645FAFBA");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("LowYurt3.Models.EnvioPedido", b =>
                {
                    b.HasOne("LowYurt3.Models.Cliente", "IdClienteNavigation")
                        .WithMany("EnvioPedidos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__Envio_Ped__Id_Cl__27F8EE98");

                    b.HasOne("LowYurt3.Models.Pago", "IdPagoNavigation")
                        .WithMany("EnvioPedidos")
                        .HasForeignKey("IdPago")
                        .IsRequired()
                        .HasConstraintName("FK__Envio_Ped__Id_Pa__2610A626");

                    b.HasOne("LowYurt3.Models.Pedido", "IdPedidoNavigation")
                        .WithMany()
                        .HasForeignKey("IdPedidoNavigationIdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdPagoNavigation");

                    b.Navigation("IdPedidoNavigation");
                });

            modelBuilder.Entity("LowYurt3.Models.Pago", b =>
                {
                    b.HasOne("LowYurt3.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdClienteNavigationIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LowYurt3.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("FK__Pago__Id_Pedido__24285DB4");

                    b.HasOne("LowYurt3.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoIdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("LowYurt3.Models.Pedido", b =>
                {
                    b.HasOne("LowYurt3.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__Pedido__Id_Clien__22401542");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("LowYurt3.Models.PedidoDetalle", b =>
                {
                    b.HasOne("LowYurt3.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("PedidoDetalles")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("FK__Pedido_De__Id_Pe__1C873BEC");

                    b.HasOne("LowYurt3.Models.Producto", "IdProductoNavigation")
                        .WithMany("PedidoDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Pedido_De__Id_Pr__1D7B6025");

                    b.HasOne("LowYurt3.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoIdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPedidoNavigation");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("LowYurt3.Models.Producto", b =>
                {
                    b.HasOne("LowYurt3.Models.Categorium", "IdCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK__Producto__Id_Cat__2334397B");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("LowYurt3.Models.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("LowYurt3.Models.Cliente", b =>
                {
                    b.Navigation("EnvioPedidos");

                    b.Navigation("Pagos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("LowYurt3.Models.Pago", b =>
                {
                    b.Navigation("EnvioPedidos");
                });

            modelBuilder.Entity("LowYurt3.Models.Pedido", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("PedidoDetalles");
                });

            modelBuilder.Entity("LowYurt3.Models.Producto", b =>
                {
                    b.Navigation("PedidoDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
